[package]
name = "puzzle"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "0.20.0-rc.1", default-features = false, features = ['std']}
puzzle-core = {path = "../../core"}